### ISSUE TITLE
Morning session: Peer-to-peer code review on Todo List Test Cases

### ISSUE THREAD

**Issue by chepkok3** [lenkon/to-do-list#9]
### Todo List Test Cases for Add Functions### 
Good work and congratulations on doing a good job. Your test is running well and all checks are passing. However, we recommend that you make some changes to improve it.

1. Add a test to confirm whether the added item is correct for the Add Item Functions by checking the item values.

**Comment by lenkon** [comment]
Hi @chepkok3,

Thanks for the valuable feedback. I have implemented the added item verification test cases.

Best regards,
K. Inoulen Shanongba

**Comment by chepkok3** [comment]
@lenkon Great!
